import React from "react";

const Select = ({ country, setCountry }) => {
  const country_list = [
    "Afghanistan 🇦🇫",
    "Albania 🇦🇱",
    "Algeria 🇩🇿",
    "Andorra 🇦🇩",
    "Angola 🇦🇴",
    "Anguilla 🇦🇮",
    "Antigua & Barbuda 🇦🇬",
    "Argentina 🇦🇷",
    "Armenia 🇦🇲",
    "Aruba 🇦🇼",
    "Australia 🇦🇺",
    "Austria 🇦🇹",
    "Azerbaijan 🇦🇿",
    "Bahamas 🇧🇸",
    "Bahrain 🇧🇭",
    "Bangladesh 🇧🇩",
    "Barbados 🇧🇧",
    "Belarus 🇧🇾",
    "Belgium 🇧🇪",
    "Belize 🇧🇿",
    "Benin 🇧🇯",
    "Bermuda 🇧🇲",
    "Bhutan 🇧🇹",
    "Bolivia 🇧🇴",
    "Bosnia & Herzegovina 🇧🇦",
    "Botswana 🇧🇼",
    "Brazil 🇧🇷",
    "British Virgin Islands 🇻🇬",
    "Brunei 🇧🇳",
    "Bulgaria 🇧🇬",
    "Burkina Faso 🇧🇫",
    "Burundi 🇧🇮",
    "Cambodia 🇰🇭",
    "Cameroon 🇨🇲",
    "Cape Verde 🇨🇻",
    "Cayman Islands 🇰🇾",
    "Chad 🇹🇩",
    "Chile 🇨🇱",
    "China 🇨🇳",
    "Colombia 🇨🇴",
    "Congo 🇨🇬",
    "Cook Islands 🇨🇰",
    "Costa Rica 🇨🇷",
    "Cote D'Ivoire 🇨🇮",
    "Croatia 🇭🇷",
    "Cuba 🇨🇺",
    "Cyprus 🇨🇾",
    "Czech Republic 🇨🇿",
    "Denmark 🇩🇰",
    "Djibouti 🇩🇯",
    "Dominica 🇩🇲",
    "Dominican Republic 🇩🇴",
    "Ecuador 🇪🇨",
    "Egypt 🇪🇬",
    "El Salvador 🇸🇻",
    "Equatorial Guinea 🇬🇶",
    "Estonia 🇪🇪",
    "Ethiopia 🇪🇹",
    "Falkland Islands 🇫🇰",
    "Faroe Islands 🇫🇴",
    "Fiji 🇫🇯",
    "Finland 🇫🇮",
    "France 🇫🇷",
    "French Polynesia 🇵🇫",
    "Gabon 🇬🇦",
    "Gambia 🇬🇲",
    "Georgia 🇬🇪",
    "Germany 🇩🇪",
    "Ghana 🇬🇭",
    "Gibraltar 🇬🇮",
    "Greece 🇬🇷",
    "Greenland 🇬🇱",
    "Grenada 🇬🇩",
    "Guam 🇬🇺",
    "Guatemala 🇬🇹",
    "Guernsey 🇬🇬",
    "Guinea 🇬🇶",
    "Guinea Bissau🇬🇼",
    "Guyana 🇬🇾",
    "Haiti 🇭🇹",
    "Honduras 🇭🇳",
    "Hong Kong 🇭🇰",
    "Hungary 🇭🇺",
    "Iceland 🇮🇸",
    "India 🇮🇳",
    "Indonesia 🇮🇩",
    "Iran 🇮🇷",
    "Iraq 🇮🇶",
    "Ireland 🇮🇪",
    "Isle of Man 🇮🇲",
    "Israel 🇮🇱",
    "Italy 🇮🇹",
    "Jamaica 🇯🇲",
    "Japan 🇯🇵",
    "Jersey 🇯🇪",
    "Jordan 🇯🇴",
    "Kazakhstan 🇰🇿",
    "Kenya 🇰🇪",
    "Kuwait 🇰🇼",
    "Kyrgyz Republic 🇰🇬",
    "Laos 🇱🇦",
    "Latvia 🇱🇻",
    "Lebanon 🇱🇧",
    "Lesotho 🇱🇸",
    "Liberia 🇱🇷",
    "Libya 🇱🇾",
    "Liechtenstein 🇱🇮",
    "Lithuania 🇱🇹",
    "Luxembourg 🇱🇺",
    "Macau 🇲🇴",
    "Macedonia 🇲🇰",
    "Madagascar 🇲🇬",
    "Malawi 🇲🇼",
    "Malaysia 🇲🇾",
    "Maldives 🇲🇻",
    "Mali 🇲🇱",
    "Malta 🇲🇹",
    "Mauritania 🇲🇷",
    "Mauritius 🇲🇺",
    "Mexico 🇲🇽",
    "Moldova 🇲🇩",
    "Monaco 🇲🇨",
    "Mongolia 🇲🇳",
    "Montenegro 🇲🇪",
    "Montserrat 🇲🇸",
    "Morocco 🇲🇦",
    "Mozambique 🇲🇿",
    "Namibia 🇳🇦",
    "Nepal 🇳🇵",
    "Netherlands 🇳🇱",
    "Netherlands Antilles 🇧🇶",
    "New Caledonia 🇳🇨",
    "New Zealand 🇳🇿",
    "Nicaragua 🇳🇮",
    "Niger 🇳🇪",
    "Nigeria 🇳🇬",
    "Norway 🇳🇴",
    "Oman 🇴🇲",
    "Pakistan 🇵🇰",
    "Palestine 🇵🇸",
    "Panama 🇵🇦",
    "Papua New Guinea 🇵🇬",
    "Paraguay 🇵🇾",
    "Peru 🇵🇪",
    "Philippines 🇵🇭",
    "Poland 🇵🇱",
    "Portugal 🇵🇹",
    "Puerto Rico 🇵🇷",
    "Qatar 🇶🇦",
    "Reunion 🇷🇪",
    "Romania 🇷🇴",
    "Russia 🇷🇺",
    "Rwanda 🇷🇼",
    "Saint Pierre & Miquelon 🇵🇲",
    "Samoa 🇼🇸",
    "San Marino 🇸🇲",
    "Saudi Arabia 🇸🇦",
    "Senegal 🇸🇳",
    "Serbia 🇷🇸",
    "Seychelles 🇸🇨",
    "Sierra Leone 🇸🇱",
    "Singapore 🇸🇬",
    "Slovakia 🇸🇰",
    "Slovenia 🇸🇮",
    "South Africa 🇿🇦",
    "South Korea 🇰🇷",
    "Spain 🇪🇸",
    "Sri Lanka 🇱🇰",
    "St Kitts & Nevis 🇰🇳",
    "St Lucia 🇱🇨",
    "St Vincent 🇻🇨",
    "St. Lucia 🇱🇨",
    "Sudan 🇸🇩",
    "Suriname 🇸🇷",
    "Swaziland 🇸🇿",
    "Sweden 🇸🇪",
    "Switzerland 🇨🇭",
    "Syria 🇸🇾",
    "Taiwan 🇹🇼",
    "Tajikistan 🇹🇯",
    "Tanzania 🇹🇿",
    "Thailand 🇹🇭",
    "Timor L'Este 🇹🇱",
    "Togo 🇹🇬",
    "Tonga 🇹🇴",
    "Trinidad & Tobago 🇹🇹",
    "Tunisia 🇹🇳",
    "Turkey 🇹🇷",
    "Turkmenistan 🇹🇲",
    "Turks & Caicos 🇹🇨",
    "Uganda 🇺🇬",
    "Ukraine 🇺🇦",
    "United Arab Emirates 🇦🇪",
    "United Kingdom 🇬🇧",
    "Uruguay 🇺🇾",
    "Uzbekistan 🇺🇿",
    "Venezuela 🇻🇪",
    "Vietnam 🇻🇳",
    "Virgin Islands (US) 🇻🇮",
    "Yemen 🇾🇪",
    "Zambia 🇿🇲",
    "Zimbabwe 🇿🇼",
  ];

  return (
    <div className="space-y-2">
      <label htmlFor="base" className="block mb-3 text-3xl text-gray-600">
        Select a country
      </label>
      <select
        value={country} onChange={(e) => setCountry(e.target.value)}
        className="bg-white border border-gray-300 text-gray-900 text-xl rounded-lg  w-96 p-2 h-[33px]"
      >
        {country_list.map((item) => (
          <option key={item} value={item}>
            {item}
          </option>
        ))}
      </select>
    </div>
  );
};

export default Select;
